spring:
  application:
    name: hello-spring-cloud-web-admin-fegin
server:
  port: 8766

#eureka:
#  client:
#    service-url:
#      default-Zone: http://localhost:8761/eureka/
eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka/
#开启hystrix
feign:
  hystrix:
    enabled: true
